import Realm from 'realm';

export const EnrollmentSchema = {
  name: 'Enrollment',
  properties: {
    _id: 'objectId',
    _annotations: 'mixed{}',
    _partition: 'string',
    _userId: 'string?',
    addressLine: 'string?',
    adminArea: 'string',
    adminAreaId: 'string',
    applicationStartTime: 'date?',
    applicationTime: 'date?',
    coveredAreaHa: 'decimal128',
    crop: 'string?',
    cropId: 'string?',
    dob: 'string',
    droughtLocationId: 'string?',
    droughtSeasonStart: 'string?',
    droughtSeasonStop: 'string?',
    droughtThresholds: 'string?',
    firstName: 'string',
    gender: 'string?',
    geoJson: 'string?',
    govId: 'string?',
    images: 'Enrollment_images[]',
    lastName: 'string',
    locality: 'string',
    localityId: 'string',
    marketingChannel: 'string?',
    mobilePhone: 'string?',
    mobilePhoneOwner: 'string?',
    notes: 'string?',
    originIds: 'string?',
    payoutMethod: 'string?',
    payoutMethodId: 'string?',
    propertyIds: 'string?',
    rainfallLocationId: 'string?',
    rainfallSeasonStart: 'string?',
    rainfallSeasonStop: 'string?',
    rainfallThresholds: 'string?',
    secondLastName: 'string?',
    spokenLanguages: 'string[]',
    status: 'string?',
    subLocality: 'string?',
    subLocalityId: 'string?',
    surveyEnabled: 'bool?',
  },
  primaryKey: '_id',
};

export const Enrollment_imagesSchema = {
  name: 'Enrollment_images',
  embedded: true,
  properties: {
    name: 'string?',
    size: 'string?',
    type: 'string?',
    uri: 'string?',
  },
};

export const UserSchema = {
  name: 'User',
  properties: {
    _id: 'string',
    _partition: 'string',
    canReadPartitions: 'string[]',
    canWritePartitions: 'string[]',
    email: 'string',
    isFirstLogin: 'bool?',
    languagesList: 'string[]',
    memberOf: 'string[]',
    mobilePhone: 'string?',
    name: 'string',
    partitionsCache: 'string[]',
  },
  primaryKey: '_id',
};

export const CampaignSchema = {
  name: 'Campaign',
  properties: {
    _id: 'objectId',
    _partition: 'string',
    description: 'string?',
    encryptionKey: 'string?',
    endTime: 'date?',
    name: 'string',
    organizer: 'objectId?',
    startTime: 'date?',
    status: 'string',
  },
  primaryKey: '_id',
};